//
//  Copyright © 2020 LabLambWorks. All rights reserved.
//

import Foundation

extension String {
    static let inventory = NSLocalizedString("Inventory", comment: "The collections of goods.")
    static let name = NSLocalizedString("Name", comment: "The reference for something.")
    static let phone = NSLocalizedString("Phone", comment: "The number for contacting.")
    static let address = NSLocalizedString("Address", comment: "A string that reference to a location.")
    static let remark = NSLocalizedString("Remark", comment: "Misc information.")
    static let lastContacted = NSLocalizedString("LastContacted", comment: "Date of last contact.")
    static let required = NSLocalizedString("Required(Input)", comment: "Cannot leave blank.")
    static let optional = NSLocalizedString("Optional(Input)", comment: "Can leave blank.")
    static let price = NSLocalizedString("Price", comment: "Price of product.")
    static let quantity = NSLocalizedString("Qty", comment: "Quantity of product.")
    static let absent = NSLocalizedString("Absent", comment: "Missing info.")
    static let customers = NSLocalizedString("Customers", comment: "The human purchasing products.")
    static let search = NSLocalizedString("Search", comment: "The action to look for something.")
    static let add = NSLocalizedString("Add", comment: "")
    static let remove = NSLocalizedString("Remove", comment: "Take away something form original place.")
    static let cameraRoll = NSLocalizedString("Photos", comment: "Collections of images.")
    static let cancel = NSLocalizedString("Cancel", comment: "Decide an event will not take place.")
    static let error = NSLocalizedString("GenericError", comment: "Error title.")
    static let OK = NSLocalizedString("OK", comment: "Word of confirming an action.")
    static let edit = NSLocalizedString("Edit", comment: "The action to change.")
    static let save = NSLocalizedString("Save", comment: "The action of storing data on disk.")
    static let orders = NSLocalizedString("Orders", comment: "")
    static let settings = NSLocalizedString("Settings", comment: "")
    static let stats = NSLocalizedString("Statistics", comment: "")
    static let orderNumber = NSLocalizedString("OrderNumber", comment: "")
    static let openedOn = NSLocalizedString("OpenedOn", comment: "")
    static let status = NSLocalizedString("Status", comment: "")
    static let all = NSLocalizedString("All", comment: "")
    static let open = NSLocalizedString("Open", comment: "")
    static let closed = NSLocalizedString("Closed", comment: "")
    static let reopen = NSLocalizedString("Reopen", comment: "")
    static let deposited = NSLocalizedString("Deposited", comment: "")
    static let paid = NSLocalizedString("Paid", comment: "")
    static let preped = NSLocalizedString("PreparedToShip", comment: "")
    static let shipped = NSLocalizedString("Shipped", comment: "")
    static let addCustomer = NSLocalizedString("AddCustomer", comment: "")
    static let membership = NSLocalizedString("Membership", comment: "")
    static let addOrderItem = NSLocalizedString("AddItem", comment: "")
    static let unexpectedErrorMsg = NSLocalizedString("ErrorExpectedMessage", comment: "")
    static let returnOrder = NSLocalizedString("ReturnOrder", comment: "")
    static let closeOrder = NSLocalizedString("Closeorder", comment: "")
    static let deleteOrder = NSLocalizedString("DeleteOrder", comment: "")
    static let sysLanguage = NSLocalizedString("SysLanguage", comment: "")
    static let inStock = NSLocalizedString("InStock", comment: "")
    static let restock = NSLocalizedString("Restock", comment: "")
    static let subtotal = NSLocalizedString("Subtotal", comment: "")
    static let restockRecord = NSLocalizedString("RestockRecord", comment: "")
    static let purchaseMembership = NSLocalizedString("PurchaseMembership", comment: "")
    static let stores = NSLocalizedString("Stores", comment: "")
    static let giveFeedback = NSLocalizedString("GiveFeedBack", comment: "")
    static let extraFeatures = NSLocalizedString("ExtraFeatures", comment: "")
    static let lastMonth = NSLocalizedString("LastMonth", comment: "")
    static let currentMonth = NSLocalizedString("CurrentMonth", comment: "")
    static let sales = NSLocalizedString("Sales", comment: "")
}
