name: Swift

on:
  pull_request:
    branches: 
      - master
      - develop

jobs:
  build:

    runs-on: macOS-latest
    strategy:
        matrix:
          destination: ['generic/platform=iOS']

    steps:
    - uses: actions/checkout@v1
    - name: pod install
      run: pod install
      shell: bash
    - name: Build
      run: |
          xcodebuild clean build -workspace KalKa.xcworkspace -scheme KalKa -destination "${destination}"
      env:
         destination: ${{ matrix.destination }}
